Pn 2113 implementazione test api web
pagopa/pn-b2b-client pull request #6
Opened 2022-09-22 14:45 UTC by EmanueleBonofiglio

2022-09-23 13:47 UTC, masciale89 requested changes

2022-09-23 13:47 UTC, masciale89 commented on src/main/java/it/pagopa/pn/client/b2b/pa/PnPaB2bUtils.java
> +            npi.pagoPaForm(newAttachment(resourcePath));
metti comunque un allegato pagopa?

2022-09-23 13:47 UTC, masciale89 commented on src/main/java/it/pagopa/pn/client/b2b/pa/PnPaB2bUtils.java
> +                .cancelledIun("")
Adesso lo IUN deve rispettare la seguente regExp: ^[A-Z]{4}-[A-Z]{4}-[A-Z]{4}-[0-9]{6}-[A-Z]{1}-[0-9]{1}$
con una lunghezza fissa di 25 caratteri. Anche il campo cancelledIun deve rispettare tale validazione.
Nel caso il campo non deve essere comunicato meglio mettere null

2022-09-23 13:47 UTC, masciale89 commented on src/main/java/it/pagopa/pn/client/b2b/pa/PnPaB2bUtils.java
> +                .group("")
anche il campo gruppo meglio mettere null se non abbiamo informazioni e non stiamo testando il comportamento del sistema con il valore corretto dei gruppi

2022-09-23 13:47 UTC, masciale89 commented on src/main/java/it/pagopa/pn/client/b2b/pa/PnPaB2bUtils.java
> +                .senderTaxId("CFComuneMilano")
quando verrà merigata la issue PN-2191
la denominazione mittente/destinatario dovrà rispettare la seguente regExp: '[^\.\"\?\!\;\:\#\$\%\(\)\*\+\/\<\>\=\@\[\]\\\^\_\{\}\|\~]+'
il TaxId mittente/destinatario questa regExp: ^(^[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z])|(^[0-9]{11})$

2022-09-23 13:47 UTC, masciale89 commented on src/main/java/it/pagopa/pn/client/b2b/pa/springconfig/BearerTokenConfiguration.java
> +}
aggiungi una riga a fine file

2022-09-23 13:47 UTC, masciale89 commented on src/test/java/it/pagopa/pn/client/b2b/pa/cucumber/test/CucumberSpringIntegration.java
>  }
aggiungi una riga a fine file

2022-09-23 13:47 UTC, masciale89 commented on src/test/java/it/pagopa/pn/client/b2b/pa/cucumber/test/steps/InvioNotificheB2bSteps.java
> +}
aggiungi una riga a fine file

2022-09-23 13:47 UTC, masciale89 commented on config/bearer-token.properties
> +pn.external.bearer-token-FieramoscaE.pagopa-dev=eyJhbGciOiAiUlMyNTYiLCJ0eXAiOiAiSldUIiwia2lkIjogIjViMDcxNTQyLTc2ZmEtNDYxOS1hM2VlLTc5MjBlZTFiNTQ4ZSJ9.eyJpYXQiOiAxNjYzMzE0ODczLCJleHAiOiAxNjk0ODUwODczLC
aggiungi una riga a fine file

2022-09-23 14:24 UTC, masciale89 approved these changes

2022-09-29 16:56 UTC, MTurraPpa commented
Inclusa nella https://github.com/pagopa/pn-b2b-client/pull/8

2022-09-29 16:56 UTC, closed without merging